// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/random_numbers.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRandomNumbersRequest contains optional event name for log routing
type GetRandomNumbersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"` // Optional event name for event-based log separation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomNumbersRequest) Reset() {
	*x = GetRandomNumbersRequest{}
	mi := &file_proto_random_numbers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomNumbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomNumbersRequest) ProtoMessage() {}

func (x *GetRandomNumbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_random_numbers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomNumbersRequest.ProtoReflect.Descriptor instead.
func (*GetRandomNumbersRequest) Descriptor() ([]byte, []int) {
	return file_proto_random_numbers_proto_rawDescGZIP(), []int{0}
}

func (x *GetRandomNumbersRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

// GetRandomNumbersResponse contains the random numbers string
type GetRandomNumbersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       string                 `protobuf:"bytes,1,opt,name=numbers,proto3" json:"numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomNumbersResponse) Reset() {
	*x = GetRandomNumbersResponse{}
	mi := &file_proto_random_numbers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomNumbersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomNumbersResponse) ProtoMessage() {}

func (x *GetRandomNumbersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_random_numbers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomNumbersResponse.ProtoReflect.Descriptor instead.
func (*GetRandomNumbersResponse) Descriptor() ([]byte, []int) {
	return file_proto_random_numbers_proto_rawDescGZIP(), []int{1}
}

func (x *GetRandomNumbersResponse) GetNumbers() string {
	if x != nil {
		return x.Numbers
	}
	return ""
}

var File_proto_random_numbers_proto protoreflect.FileDescriptor

const file_proto_random_numbers_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/random_numbers.proto\x12\rrandomnumbers\"8\n" +
	"\x17GetRandomNumbersRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\"4\n" +
	"\x18GetRandomNumbersResponse\x12\x18\n" +
	"\anumbers\x18\x01 \x01(\tR\anumbers2z\n" +
	"\x13RandomNumberService\x12c\n" +
	"\x10GetRandomNumbers\x12&.randomnumbers.GetRandomNumbersRequest\x1a'.randomnumbers.GetRandomNumbersResponseB6Z4github.com/neeharmavuduru/logger-double-buffer/protob\x06proto3"

var (
	file_proto_random_numbers_proto_rawDescOnce sync.Once
	file_proto_random_numbers_proto_rawDescData []byte
)

func file_proto_random_numbers_proto_rawDescGZIP() []byte {
	file_proto_random_numbers_proto_rawDescOnce.Do(func() {
		file_proto_random_numbers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_random_numbers_proto_rawDesc), len(file_proto_random_numbers_proto_rawDesc)))
	})
	return file_proto_random_numbers_proto_rawDescData
}

var file_proto_random_numbers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_random_numbers_proto_goTypes = []any{
	(*GetRandomNumbersRequest)(nil),  // 0: randomnumbers.GetRandomNumbersRequest
	(*GetRandomNumbersResponse)(nil), // 1: randomnumbers.GetRandomNumbersResponse
}
var file_proto_random_numbers_proto_depIdxs = []int32{
	0, // 0: randomnumbers.RandomNumberService.GetRandomNumbers:input_type -> randomnumbers.GetRandomNumbersRequest
	1, // 1: randomnumbers.RandomNumberService.GetRandomNumbers:output_type -> randomnumbers.GetRandomNumbersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_random_numbers_proto_init() }
func file_proto_random_numbers_proto_init() {
	if File_proto_random_numbers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_random_numbers_proto_rawDesc), len(file_proto_random_numbers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_random_numbers_proto_goTypes,
		DependencyIndexes: file_proto_random_numbers_proto_depIdxs,
		MessageInfos:      file_proto_random_numbers_proto_msgTypes,
	}.Build()
	File_proto_random_numbers_proto = out.File
	file_proto_random_numbers_proto_goTypes = nil
	file_proto_random_numbers_proto_depIdxs = nil
}
