// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/random_numbers.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RandomNumberService_GetRandomNumbers_FullMethodName = "/randomnumbers.RandomNumberService/GetRandomNumbers"
)

// RandomNumberServiceClient is the client API for RandomNumberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RandomNumberService provides endpoints for generating random numbers
type RandomNumberServiceClient interface {
	// GetRandomNumbers returns 200 random numbers separated by ':'
	GetRandomNumbers(ctx context.Context, in *GetRandomNumbersRequest, opts ...grpc.CallOption) (*GetRandomNumbersResponse, error)
}

type randomNumberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRandomNumberServiceClient(cc grpc.ClientConnInterface) RandomNumberServiceClient {
	return &randomNumberServiceClient{cc}
}

func (c *randomNumberServiceClient) GetRandomNumbers(ctx context.Context, in *GetRandomNumbersRequest, opts ...grpc.CallOption) (*GetRandomNumbersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRandomNumbersResponse)
	err := c.cc.Invoke(ctx, RandomNumberService_GetRandomNumbers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RandomNumberServiceServer is the server API for RandomNumberService service.
// All implementations must embed UnimplementedRandomNumberServiceServer
// for forward compatibility.
//
// RandomNumberService provides endpoints for generating random numbers
type RandomNumberServiceServer interface {
	// GetRandomNumbers returns 200 random numbers separated by ':'
	GetRandomNumbers(context.Context, *GetRandomNumbersRequest) (*GetRandomNumbersResponse, error)
	mustEmbedUnimplementedRandomNumberServiceServer()
}

// UnimplementedRandomNumberServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRandomNumberServiceServer struct{}

func (UnimplementedRandomNumberServiceServer) GetRandomNumbers(context.Context, *GetRandomNumbersRequest) (*GetRandomNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomNumbers not implemented")
}
func (UnimplementedRandomNumberServiceServer) mustEmbedUnimplementedRandomNumberServiceServer() {}
func (UnimplementedRandomNumberServiceServer) testEmbeddedByValue()                             {}

// UnsafeRandomNumberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RandomNumberServiceServer will
// result in compilation errors.
type UnsafeRandomNumberServiceServer interface {
	mustEmbedUnimplementedRandomNumberServiceServer()
}

func RegisterRandomNumberServiceServer(s grpc.ServiceRegistrar, srv RandomNumberServiceServer) {
	// If the following call pancis, it indicates UnimplementedRandomNumberServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RandomNumberService_ServiceDesc, srv)
}

func _RandomNumberService_GetRandomNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomNumberServiceServer).GetRandomNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RandomNumberService_GetRandomNumbers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomNumberServiceServer).GetRandomNumbers(ctx, req.(*GetRandomNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RandomNumberService_ServiceDesc is the grpc.ServiceDesc for RandomNumberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RandomNumberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "randomnumbers.RandomNumberService",
	HandlerType: (*RandomNumberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomNumbers",
			Handler:    _RandomNumberService_GetRandomNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/random_numbers.proto",
}
